### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Koala4ka** [Koala4ka/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Koala4ka** [comment]
I am a self-motivated, enthusiastic programmer, I have experience in pet
projects with the team. Besides, I write my own projects, which I sometimes publish at GitHub.
I like to take on new challenges and strive to overcome them effectively and on time.
I have a strong passion for self-development and obtaining new knowledge and experience
by performing complex tasks. At the moment, I know that I am ready to get real
commercial experience in a company or a startup.

**Comment by lemur4ek** [comment]
I am a self-motivated, enthusiastic programmer, I have experience in pet
projects with the team. Besides, I write my own projects, which I sometimes publish at GitHub.
I like to take on new challenges and strive to overcome them effectively and on time.
I have a strong passion for self-development and obtaining new knowledge and experience
by performing complex tasks. At the moment, I know that I am ready to get real
commercial experience in a company or a startup.

**Comment by Koala4ka** [comment]
thanks a lot)
