### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Koala4ka** [Koala4ka/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by lemur4ek** [comment]
**W O R K
E X P E R I E N C E**
QA Engineer
Dinarys | Oct 2019 - Dec 2019
Made Test Plans, Test Cases, Check List and Bug Reports
**E D U C A T I O N A L
H I S T O R Y**
- Java | Jun 2020 - Oct 2020
CURSOR Education
Java core, java EE
- Java | Dec 2019 - March 2020
"SOLVVE"
Java course backed Spring boot
- Jul 2019 - Oct 2019
SkillUp
Software testing, basic WEB and SQL curse
- Bachelor | Sep 2013 - Jun 2017
National Mining University
Scientific and technical translation
