### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Koala4ka** [Koala4ka/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by lemur4ek** [comment]
**S K I L L S S U M M A R Y**
- Java Core
- Spring:WebFlux
- JDBC
- GIT 
- SQL 
- AWS/GCP
- HTML/CSS
- JS
- Linux/Windows

**L A N G U A G E S**
- English B2
- German B1

**HOBBIES**

- games :woman_technologist:
- karaoke and dance :dancer:
- baking pancakes :cook:
